version: "3"

services: 
  web:
    image: pojntfx/opensdcp-website:latest
    ports:
      - "80:5000"
    deploy:
      replicas: 5
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure
