version: "3"

services: 
  web:
    image: node:latest
    ports:
      - 3000:3000
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command: "npm run dev"
    deploy:
      replicas: 5
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure