apiVersion: v1
kind: Service
metadata:
  name: opensdcp-website-web
spec:
  selector:
    app: opensdcp-website-web
    tier: backend
    track: stable
  ports:
    - name: web
      targetPort: web
      port: 80
  type: NodePort